### ISSUE TITLE
Where are the Maki icons webfont coming from?

### ISSUE THREAD

**Issue by abenrob** [QwantResearch/qwantmaps#107]
I see you are using a webfont generated from the Maki iconset, but I can't find where the code is to generate this. https://www.qwant.com/maps/mapstyle/iconfont/iconfont.css

Can you point me to this? I'm trying to generate the same thing, but getting errors from my generator, so very curious how you are doing it.

**Comment by amatissart** [comment]
The webfont generation is actually implemented in our [map-style-builder](https://github.com/QwantResearch/map-style-builder), specifically in this file: https://github.com/QwantResearch/map-style-builder/blob/master/task/webfont/index.js

For the moment this implementation is quite specific to our style [qwant-basic-gl-style](https://github.com/QwantResearch/qwant-basic-gl-style). It will parse .svg files from the "icons" directory, and ignore any `<rect>` element (in order to remove the border from each icon).

An example for how it's used in our build is visible here: 
https://github.com/QwantResearch/erdapfel/blob/master/build/before_build.js#L10-L21

I hope that helps a little.

**Comment by abenrob** [comment]
Awesome. Thanks!
I was using `webfonts-generator` as well, but getting loading issues from what was generated - I think the cleanup stuff you guys put in there solved my issue.
Merci pour la réponse !
