### ISSUE TITLE
Filter search by closest results from the user position

### ISSUE THREAD

**Issue by Booteille** [QwantResearch/qwantmaps#58]
I think that would be useful to use the position given by the user when searching something on Qwant Map to get more accurate results about what the user could wants.

I am living in point A and told it as the reference position on Qwant Maps.
I want to go to the closest bakery. So I type "bakery" on the destination field.
The issue is that I get bakeries for things far away from my position and I have to add the name of the city where I want to go to get results from it.

Here are two screenshots to illustrate that.
![maps_issue_01](https://user-images.githubusercontent.com/2203721/59914029-c57e6900-9419-11e9-9ec5-682a98b7d9e9.png)
![maps_issue_02](https://user-images.githubusercontent.com/2203721/59914030-c57e6900-9419-11e9-8c15-65b6609f0e41.png)

**Comment by jbgriesner** [comment]
Thanks for this relevant feedback.
Indeed, you are completely right !
We are currently working precisely on this feature: it should be released very soon, after non-regression tests.

**Comment by Booteille** [comment]
Great to read that! Thanks!

**Comment by amatissart** [comment]
Some improvements have been implemented and deployed recently about this issue.  
Thanks to https://github.com/CanalTP/mimirsbrunn/pull/308 and https://github.com/QwantResearch/erdapfel/pull/291, queries that are typed while on zoom >= 11 will now favor closer results.

Other features are to come in order to handle generic queries (such as "Bakery") more conveniently. But this is not specific to this issue.
