### ISSUE TITLE
results do not match the search terms

### ISSUE THREAD

**Issue by jpalexandre** [QwantResearch/qwantmaps#74]
I just want to inform about this issue, results missmatch >> see attached file fore more information
![QwantMAP_Rem02072019](https://user-images.githubusercontent.com/52456106/60515002-f6448500-9cda-11e9-9d97-369f13b85948.JPG)

**Comment by jbgriesner** [comment]
Thanks for your feedback.
In order to understand better the "missmatch" you mentioned, could you please provide us more context about:
- what you exactly did: I guess you typed "techniflex" and you pressed the "return" key isn't ?  
- what you expected: which point-of-interest exactly were you looking for ?
- your technical environment: what is the search language of your browser ?...
