### ISSUE TITLE
POI non found and strange result whith "coiffure"

### ISSUE THREAD

**Issue by lenny31** [QwantResearch/qwantmaps#79]
Hi !
I search "coiffure Beauzelle" Qwant found 3 POI in Beauzelle
I search "coiffeur Beauzelle" Qwant found 7 POI not in Beauzelle : in Grece, Salzburg, Wien ...

Qwant dont find  Hom' Modern coiffeur 
2 Rue des Pins (Beauzelle) 

![coiffureBeauzelle](https://user-images.githubusercontent.com/7862384/60737765-2d759900-9f5c-11e9-9214-33288423675e.jpg)

**Comment by jbgriesner** [comment]
Thanks for your issue. First of all the current version of the Qwant Maps research engine allows you to search _only_ for "exact" places. Exact places mean that the assumption we make is that your query is associated to only one specific place on the map. Here your query "coiffure Beauzelle" does not match only one place: it looks more like a _category_ which can matches many places.

Based on this assumption, regarding your first problem, Qwant Maps finds 3 POI with "coiffure Beauzelle" only because these 3 POI have "coiffure" in their names.


However I can find it if I just type "Hom modern" as you can see:
![coiff1](https://user-images.githubusercontent.com/33450151/61207959-a44a2900-a6f6-11e9-9524-16fe53d4fb8a.png)
![coiff2](https://user-images.githubusercontent.com/33450151/61207964-a7451980-a6f6-11e9-935c-0b0bab3db167.png)

**Comment by lenny31** [comment]
Sorry, I thought the search was also done by category using OSM tags, because when you select these POIs, below the name it says "coiffeur" and the corresponding icon is displayed on the map. 
![image](https://user-images.githubusercontent.com/7862384/61248867-43e9d480-a754-11e9-8a15-3bf97e67444d.png)
